// Generated by CoffeeScript 1.10.0
$(function() {
  return $('#submit').click(function() {
    var http, params, url;
    http = new XMLHttpRequest();
    url = 'http://localhost:8000/api';
    params = "title=" + ($('#title').val()) + "&content=" + ($('#content').val());
    http.open("POST", url, true);
    return http.send(params);
  });
});

//# sourceMappingURL=popup.js.map
