// Generated by CoffeeScript 1.10.0
$(function() {
  var article;
  article = JSON.stringify({
    title: $('#title').val(),
    content: $('#content').val()
  });
  return $('#submit').click(function() {
    return $.ajax({
      type: 'POST',
      url: 'http://localhost:8000/api',
      dataType: 'json',
      data: article,
      error: function() {},
      success: function() {}
    });
  });
});

//# sourceMappingURL=popup.js.map
